### ISSUE TITLE
Unique User ID (UUID)

### ISSUE THREAD

**Issue by BennerLukas** [BennerLukas/Tracer#3]
UUID:
- randon hash
- simple count up -> binary search possible (Fast!)

**Comment by Madhour** [comment]
I Implemented it with [CUID](https://deno.land/x/cuid@v1.0.0). 
A simple count up poses security risks as malicious users can assume their ID±1 will lead to another valid ID. 
This is a classic performance and security tradeoff, but since privacy is valued more I suggest we continue w/ CUIDs.

Feel free to reopen if you have any performance concerns.
